# Generated by Django 5.2.8 on 2025-11-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_scores', to='games.game'),
        ),
    ]
